# Generated by Django 4.0.2 on 2022-03-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='postlist',
            name='category',
            field=models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('FullStack', 'FullStack')], default='FS', max_length=100),
        ),
    ]
