# Generated by Django 4.0.2 on 2022-03-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_name_comments_user_postlist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='name',
        ),
    ]
