# Generated by Django 4.0.2 on 2022-03-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_user_comments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='user',
        ),
    ]
